input {
  http {
    host => "localhost"
    port => "5100"
    method => "POST"

    request_content_type => "application/json"

    parse {
        key => "_json"
        type => "json"
    }
  }
}

output {
  opensearch {
    hosts => ["https://opensearch:9200"]
    index => "wetter-%{+YYYY.MM.dd}"
    user => "admin"
    password => "admin"
    ssl_certificate_verification => false
  }
}


